### ISSUE TITLE
RuntimeError: The size of tensor a (4) must match the size of tensor b (64) at non-singleton dimension 1

### ISSUE THREAD

**Issue by ponyling** [jaiwei98/MobileNetV4-pytorch#2]
Hello, thank you very much for your open-source code! However, I encountered a problem when running MobileNetV4HybridMedium and MobileNetV4HybridLarge.
The error message is 
```
File "/model/mobilenetv4.py", line 187, in forward
attn_score = torch.matmul(q, k) / (self.head_dim ** 0.5)
RuntimeError: The size of tensor a (4) must match the size of tensor b (64) at non-singleton dimension 1
```
At this time, my model is MobileNetV4HybridMedium, with batch_size=64. The printed information is "Size of q tensor:([64, 4, 196, 64])
Size of k tensor:([64, 64, 49])".

**Comment by jaiwei98** [comment]
Hi @ponyling, 
Thank you for pointing this bug. The latest commit should fixed this problem, kindly have a look. Cheers!
