### ISSUE TITLE
RuntimeError: The size of tensor a (4) must match the size of tensor b (1000) at non-singleton dimension 1

### ISSUE THREAD

**Issue by xuefei4545** [jaiwei98/MobileNetV4-pytorch#5]
你好，加入注意力机制的v4，在batchsize不为1的时候会出现维度错误，应该是mhsa部分出现的问题。
import torch
from mobilenetv4 import MobileNetV4

# Support ['MobileNetV4ConvSmall', 'MobileNetV4ConvMedium', 'MobileNetV4ConvLarge']
# Also supported ['MobileNetV4HybridMedium', 'MobileNetV4HybridLarge']
model = MobileNetV4("MobileNetV4HybridMedium")

# Check the trainable params
total_params = sum(p.numel() for p in model.parameters())
print(f"Number of parameters: {total_params}")

# Check the model's output shape
print("Check output shape ...")
x = torch.rand(2, 3, 224, 224)
y = model(x)
for i in y:
    print(i.shape)
    
Number of parameters: 9787472
Check output shape ...
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[7], line 15
     13 print("Check output shape ...")
     14 x = torch.rand(2, 3, 224, 224)
---> 15 y = model(x)
     16 for i in y:
     17     print(i.shape)

File [d:\ProgramFiles\anaconda\envs\xf\lib\site-packages\torch\nn\modules\module.py:1501](file:///D:/ProgramFiles/anaconda/envs/xf/lib/site-packages/torch/nn/modules/module.py:1501), in Module._call_impl(self, *args, **kwargs)
   1496 # If we don't have any hooks, we want to skip the rest of the logic in
   1497 # this function, and just call forward.
   1498 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1499         or _global_backward_pre_hooks or _global_backward_hooks
   1500         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1501     return forward_call(*args, **kwargs)
   1502 # Do not call functions when jit is used
   1503 full_backward_hooks, non_full_backward_hooks = [], []

File [d:\DMS\InsightFace_Pytorch-master\mobilenetv4.py:321](file:///D:/DMS/InsightFace_Pytorch-master/mobilenetv4.py:321), in MobileNetV4.forward(self, x)
    319 x1 = self.layer1(x0)
    320 x2 = self.layer2(x1)
--> 321 x3 = self.layer3(x2)
    322 x4 = self.layer4(x3)
    323 x5 = self.layer5(x4)
...
--> 179 attn_score = torch.matmul(q, k) / (self.head_dim ** 0.5)
    180 attn_score = self.dropout(attn_score)
    181 attn_score = F.softmax(attn_score, dim=-1)

RuntimeError: The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 1

**Comment by jaiwei98** [comment]
Hi @xuefei4545,

This should be fixed in the last commits. 
Please try pull the latest code and try again 😉 

Thank you.
