### ISSUE TITLE
there is a bug，at Multi Query Attention with spatial downsampling model

### ISSUE THREAD

**Issue by 2991535823** [jaiwei98/MobileNetV4-pytorch#8]
hello, i try to run this code but I faced a bug. due to my poor code ability， so I submit the bug。i know the problem reason， but I don't know how to fix it。please give help，thanks！
```python
q = F.avg_pool2d(self.query_h_strides, self.query_w_strides)
TypeError: avg_pool2d(): argument 'input' (position 1) must be Tensor, not int
```

**Comment by jaiwei98** [comment]
Hello, can you provide a minimal code to reproduce this error?

**Comment by 2991535823** [comment]
ok，I&nbsp;will&nbsp;provide&nbsp;the&nbsp;code&nbsp;later&nbsp;(maybe&nbsp;two&nbsp;days)&nbsp;because&nbsp;there&nbsp;is&nbsp;no&nbsp;computer&nbsp;around


---Original---
From: ***@***.***&gt;
Date: Fri, May 31, 2024 21:18 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [jaiwei98/MobileNetV4-pytorch] there is a bug，at Multi Query Attention with spatial downsampling model (Issue #8)




 
Hello, can you provide a minimal code to reproduce this error?
 
&mdash;
